<%= File.read(File.join(File.dirname(__FILE__), '../../courseware_book.yml')) %>

salesforce_book_name: AP Physics
appearance_code: ap_physics
default_course_name: AP Physics
cnx_book_id: 8d04a686-d5e8-4798-a27d-c608e4d0e187

reading_processing_instructions:
- css: .conceptual-questions, .problems-exercises, [data-element-type="conceptual-questions"],
    [data-element-type="problems-exercises"], [data-element-type="check-understanding"],
    [data-type="glossary"]
  fragments: []
- css: .phet-explorations-embedded
  fragments:
  - interactive
  - exercise
- css: .watch-physics
  fragments:
  - video
  - exercise
- css: .example-video, [data-type="example"]
  fragments:
  - reading
