<%= File.read(File.join(File.dirname(__FILE__), '../../courseware_book.yml')) %>

salesforce_book_name: Biology 2e
appearance_code: biology_2e
default_course_name: Biology 2e
cnx_book_id: 8d50a0af-948b-4204-a71d-4826cba765b8@15.1

reading_processing_instructions:
- css: .multiple-choice, .free-response, .art-exercise, .interactive-embedded-homework,
    .scientific, [data-type="glossary"]
  fragments: []
- css: .interactive-embedded-reading
  fragments:
  - node
  - exercise
