OSU::AccessPolicy.register(Course, CourseAccessPolicy)
OSU::AccessPolicy.register(Klass, KlassAccessPolicy)
OSU::AccessPolicy.register(Student, StudentAccessPolicy)
OSU::AccessPolicy.register(Task, TaskAccessPolicy)
OSU::AccessPolicy.register(User, UserAccessPolicy)
