      tasks:
        - student:
            username: reviewstudent1
          progress: 0
        - student:
            username: reviewstudent3
          progress: 0
        - student:
            username: reviewstudent5
          progress: 0
