---
# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at http://help.apm.scoutapp.com#environment-variables for more information.
development:
  monitor: false

test:
  monitor: false

production:
  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: <%= ENV['SCOUT_LICENSE_KEY'] %>

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  # log_level: debug

  # name: application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  name: tutor (<%= ENV['ENVIRONMENT_NAME'] %>)

  # monitor: Enable Scout APM or not
  # - Default: false
  # - Valid Options: true, false
  monitor: true

  # ignore: An Array of web endpoints that Scout should not instrument.
  # Routes that match the prefixed path (ex: ['/health', '/status']) will be ignored by the agent.
  # - Default: []
  ignore:
    - /ping
