book:
  run: FactoryBot.create :mini_ecosystem
  style: college-physics

catalog_offering:
  title: Second Mini Physics with Courseware
  salesforce_book_name: Physics w Courseware
  appearance_code: college_physics
