book:
  uuid: 405335a3-7cff-4df2-a9ad-29062a4af261
  style: college-physics

catalog_offering:
  title: Physics with Courseware
  salesforce_book_name: Physics w Courseware
  appearance_code: college_physics
