book:
  archive_url_base: https://archive.cnx.org/contents/

  uuid: 405335a3-7cff-4df2-a9ad-29062a4af261

  reading_processing_instructions:
    - css: .conceptual-questions, .problems-exercises, [data-element-type="conceptual-questions"],
        [data-element-type="problems-exercises"], [data-element-type="check-understanding"],
        [data-type="glossary"]
      fragments: []
    - css: '[data-type="footnote-refs"]'
      fragments:
      - media
    - css: .phet-explorations-embedded
      fragments:
      - interactive
      - exercise
      labels:
      - phet-explorations
    - css: .watch-physics
      fragments:
      - video
      - exercise
      labels:
      - watch-physics
    - css: .example-video, [data-type="example"]
      fragments:
      - reading
      labels:
      - example

catalog_offering:
  title: Physics with Courseware
  salesforce_book_name: Physics w Courseware
  appearance_code: college_physics
