book:
  archive_url_base: https://openstax.org/apps/archive/20201222.172624/contents/

  uuid: 02040312-72c8-441e-a685-20e9333f3e1d

  reading_processing_instructions:
    - css: .section-quiz, .short-answer, .further-research, [data-element-type="section-quiz"],
        [data-element-type="short-answer"], [data-element-type="further-research"],
        [data-type="glossary"]
      fragments: []

catalog_offering:
  title: Sociology with Courseware
  salesforce_book_name: Sociology w Courseware
  appearance_code: intro_sociology
