    tasks:
      - student:
          username: reviewstudent1
        progress: 1
        score: 1
      - student:
          username: reviewstudent2
        progress: 1
        score: .8
      - student:
          username: reviewstudent3
        progress: .66
        score: .5
      - student:
          username: reviewstudent4
        progress: 1
        score: 1
      - student:
          username: reviewstudent5
        progress: 1
        score: .8
      - student:
          username: reviewstudent6
        progress: .66
        score: .5
