name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: ci_test
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        tests:
            - { name: 'fast'  , args: 'TAG=speed:fast'   }
            - { name: 'medium', args: 'TAG=speed:medium' }
            - { name: 'slow'  , args: 'TAG=speed:slow'   }
            - { name: 'assets', args: 'ASSETS=true'      }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-pr-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-pr-
      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          OXT_DB_USER: postgres
          OXT_TEST_DB: ci_test
          OXT_DB_PASS: postgres
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bin/rails assets:precompile
          ${{ matrix.tests.args }} ./bin/ci
